{% set name = "pysheds" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 039d89e3f798e75649b46bc01ca04f0465ea092ba58f63de124cf6bd5cfa1a4b

build:
  number: 0
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
  run:
    - python
    - numba
    - numpy
    - pandas
    - scipy
    - pyproj
    - scikit-image
    - affine
    - geojson
    - rasterio >=1

test:
  imports:
    - pysheds
    - pysheds.grid
    - pysheds.view
    - pysheds.io

about:
  home: http://github.com/mdbartos/pysheds
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Simple and fast watershed delineation in python.
  description: |
    Simple and fast watershed delineation in python.
  doc_url: https://mdbartos.github.io/pysheds/
  dev_url: https://github.com/mdbartos/pysheds

extra:
  recipe-maintainers:
    - mdbartos
