{% set name = "pysheds" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 039d89e3f798e75649b46bc01ca04f0465ea092ba58f63de124cf6bd5cfa1a4b

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - cython                              # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]
  host:
    - cython
    - numpy
    - python
    - pip
  run:
    - python
    - affine
    - geojson
    - looseversion
    - numba
    - {{ pin_compatible('numpy') }}
    - pandas
    - pyproj
    - rasterio >=1
    - scikit-image
    - scipy

test:
  imports:
    - pysheds
    - pysheds.grid
    - pysheds.view
    - pysheds.io

about:
  home: https://github.com/mdbartos/pysheds
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Simple and fast watershed delineation in python.
  description: |
    Simple and fast watershed delineation in python.
  doc_url: https://mdbartos.github.io/pysheds/
  dev_url: https://github.com/mdbartos/pysheds

extra:
  recipe-maintainers:
    - Zeitsperre
    - mdbartos
