{% set name = "pysheds" %}
{% set version = "0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b56fb478ed3e4194b6d0a0033c66dcdc5dafafd90dbc05ad096ffb450e6a8005

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - python {{ python_min }}             # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - cython                              # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]
  host:
    - cython
    - numpy
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python
    - affine
    - geojson
    - looseversion
    - numba
    - numpy
    - pandas
    - pyproj
    - rasterio >=1
    - scikit-image
    - scipy

test:
  imports:
    - pysheds
    - pysheds.grid
    - pysheds.view
    - pysheds.io
  requires:
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/mdbartos/pysheds
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Simple and fast watershed delineation in python.
  description: |
    Simple and fast watershed delineation in python.
  doc_url: https://mdbartos.github.io/pysheds/
  dev_url: https://github.com/mdbartos/pysheds

extra:
  recipe-maintainers:
    - Zeitsperre
    - mdbartos
