{% set name = "pysheds" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2a22d43d408bebe759704f20f9ae0560566a85ea545d644f65ad44978d6a88ac

build:
  number: 2
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - pandas
    - scipy
    - pyproj
    - scikit-image
    - affine
    - geojson
    - rasterio >=1

test:
  imports:
    - pysheds
    - pysheds.grid

about:
  home: http://github.com/mdbartos/pysheds
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Simple and fast watershed delineation in python.
  description: |
    Simple and fast watershed delineation in python.
  doc_url: https://mdbartos.github.io/pysheds/
  dev_url: https://github.com/mdbartos/pysheds

extra:
  recipe-maintainers:
    - mdbartos
